name: bloging_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dotted_border: ^2.1.0
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  fpdart: ^1.1.1
  get_it: ^8.0.3
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0
  image_picker: ^1.1.2
  internet_connection_checker_plus: ^2.7.0
  intl: ^0.20.1
  supabase_flutter: ^2.8.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/core/constants/secrets/app_secrets.env
